blueprint:
  name: Dreame Vacuum - Updating the to clean list
  description: >
    Updates the cleaning queue when the robot starts or changes rooms.

    ### Search Regex List:
    - **Queue Text Helper:** `^input_text\..*_rooms_to_clean$`
    - **Currently Cleaning Helper:** `^input_number\..*_currently_cleaned$`

    ### Data Format Requirements:
    - **Queue Format:** Must be a comma-separated list, optionally wrapped in brackets. 
      *Example:* `[1, 5, 12]` or `1,5,12`
    - **Helper Association:** Both helpers must be assigned to the same **Device** as the vacuum robot in Home Assistant.
  domain: automation
  input:
    vacuum_entity:
      name: Vacuum Robot
      selector:
        entity:
          domain: vacuum
          integration: dreame_vacuum

mode: single

# 1. TRIGGER: Specifically watching for undocking and segment transitions
trigger:
  - trigger: state
    entity_id: !input vacuum_entity
    from: docked
    to: cleaning
  - trigger: state
    entity_id: !input vacuum_entity
    attribute: current_segment

variables:
  # 2. IDENTIFY DEVICE & ENTITIES
  vacuum_ent: !input vacuum_entity
  dev_id: "{{ device_id(vacuum_ent) }}"
  dev_entities: >-
    {% set all_labels = (labels(vacuum_ent)) | unique %}
    {% set labeled_entities = all_labels | map('label_entities') | sum(start=[]) %}
    {{ (device_entities(dev_id) + labeled_entities) | unique | list }}

  # 3. DYNAMIC ENTITY DISCOVERY
  text_helper: "{{ dev_entities | select('match', '^input_text\\..*_rooms_to_clean$') | first | default('none') }}"
  currently_cleaned_helper: "{{ dev_entities | select('match', '^input_number\\..*_currently_cleaned$') | first | default('none') }}"

action:
  # Check Step 3: Notify if helpers are missing
  - if:
      - condition: template
        value_template: "{{ text_helper == 'none' or currently_cleaned_helper == 'none' }}"
    then:
      - action: persistent_notification.create
        data:
          title: "Vacuum Queue Manager Error"
          message: "Helpers not found for device {{ dev_id }}. Text: {{ text_helper }}, Number: {{ currently_cleaned_helper }}."
      - stop: "Required helpers missing"

  - variables:
      # 4. PARSE CURRENT QUEUE
      current_queue: >-
        {% set val = states(text_helper) %}
        {% if val not in ['unknown', 'unavailable', ''] %}
          {% set raw = val | replace('[', '') | replace(']', '') | replace(' ', '') %}
          {{ raw.split(',') | map('int', 0) | select('gt', 0) | list }}
        {% else %}
          []
        {% endif %}
      # 5. GET ACTIVE SEGMENT FROM ATTRIBUTE
      active_segment: "{{ state_attr(vacuum_ent, 'current_segment') | int(0) }}"

  # Check Step 4: Notify if queue parsing failed (empty result from non-empty input)
  - if:
      - condition: template
        value_template: "{{ current_queue | length == 0 and states(text_helper) not in ['unknown', 'unavailable', '', '[]'] }}"
    then:
      - action: persistent_notification.create
        data:
          title: "Vacuum Queue Parsing Error"
          message: "Queue empty but input was: '{{ states(text_helper) }}'. Check format."

  # 6. STOP IF QUEUE IS EMPTY
  - condition: template
    value_template: "{{ current_queue | length > 0 }}"

  # 7. UPDATE HELPERS IF ROBOT IS IN THE TARGET ROOM
  - if:
      - condition: template
        value_template: "{{ active_segment == current_queue[0] }}"
    then:
      # Update the "Currently Cleaned" helper with the current segment
      - action: input_number.set_value
        target:
          entity_id: "{{ currently_cleaned_helper }}"
        data:
          value: "{{ active_segment }}"
      # Shift the queue: Remove the first item as it is now being cleaned
      - action: input_text.set_value
        target:
          entity_id: "{{ text_helper }}"
        data:
          value: "[{{ current_queue[1:] | join(',') }}]"
