blueprint:
  name: Dreame Vacuum - Reset and Notify
  description: Resets helpers, creates a To-Do, and clears specific vacuum notifications when finished.
  domain: automation
  input:
    vacuum_entity:
      name: Vacuum Robot
      selector:
        entity:
          domain: vacuum
          integration: dreame_vacuum
    todo_list:
      name: To-Do List
      selector:
        entity:
          domain: todo
    todo_header_text:
      name: To-Do Header Text
      default: "Robot Cleaning"
      selector:
        text:
    notify_script:
      name: Notification Script
      selector:
        entity:
          domain: script

mode: single

triggers:
  # Listens for the specific completion event from the Dreame integration
  - trigger: event
    event_type: dreame_vacuum_task_status
    event_data:
      completed: true

variables:
  vacuum_ent: !input vacuum_entity 
  dev_id: "{{ device_id(vacuum_ent) }}"
  # Extracts the MAC address from attributes to match the dismissal ID format
  mac_addr: "{{ state_attr(vacuum_ent, 'mac_address') }}"
  
  # Logic to find helper entities associated with the device (via labels or ID)
  dev_entities: >-
    {% set all_labels = (labels(vacuum_ent)) | unique %}
    {% set labeled_entities = all_labels | map('label_entities') | sum(start=[]) %}
    {{ (device_entities(dev_id) + labeled_entities) | unique | list }}
  
  text_helper: "{{ dev_entities | select('match', '^input_text\\..*_rooms_to_clean$') | first | default('none') }}"
  currently_cleaned_helper: "{{ dev_entities | select('match', '^input_number\\..*_currently_cleaned$') | first | default('none') }}"

conditions:
  - condition: template
    value_template: >-
      {{ trigger.event.data.entity_id.startswith(vacuum_ent) }}

action:
  # 1. Reset the Text Helper (Clear the room queue)
  - if:
      - condition: template
        value_template: "{{ text_helper != 'none' }}"
    then:
      - action: input_text.set_value
        target:
          entity_id: "{{ text_helper }}"
        data:
          value: "[]"

  # 2. Reset the Counter Helper (Currently cleaned rooms)
  - if:
      - condition: template
        value_template: "{{ currently_cleaned_helper != 'none' }}"
    then:
      - action: input_number.set_value
        target:
          entity_id: "{{ currently_cleaned_helper }}"
        data:
          value: 0

  # 3. Create a To-Do item for maintenance
  - action: todo.get_items
    target:
      entity_id: !input todo_list
    data:
      status: needs_action
    response_variable: current_todos

  - action: script.conditional_to_do_creator
    data:
      heading: !input todo_header_text
      body: Replace water and clean the robot

  # 4. Execute your custom notification script
  - action: script.turn_on
    target:
      entity_id: !input notify_script
    data:
      variables:
        message: "The vacuum has finished cleaning and is back at the dock. Please remember to clean the robot and replace the water."
