blueprint:
  name: Calendar-Based Vacuum with Task Check
  description: >
    Starts a vacuum script based on a calendar event, but only if a specific 
    maintenance task is not present on your To-Do list.
  domain: automation
  input:
    vacuum_entity:
      name: Vacuum Robot
      selector:
        entity:
          domain: vacuum
          integration: dreame_vacuum
    calendar_entity:
      name: Calendar
      selector:
        entity:
          domain: calendar
    calendar_summary_match:
      name: Event Summary Filter
      default: "eg auto cleaning"
    todo_entity:
      name: To-Do List
      selector:
        entity:
          domain: todo
    todo_search_term:
      name: To-Do Search Term
      default: "clean eg robot"
    cleaning_script:
      name: Cleaning Script
      selector:
        entity:
          domain: script
    ignore_rooms:
      name: Ignored Rooms
      description: "List of room IDs to exclude from cleaning (e.g. [1, 5])"
      default: []
      selector:
        object:
    cleaning_mode_select:
      name: Cleaning Mode Selector
      description: Input select to set to 'Vacuum and Mop' before cleaning.
      default: input_select.cleaning_type_selector
      selector:
        entity:
          domain: input_select

variables:
  vacuum_ent: !input vacuum_entity
  dev_id: "{{ device_id(vacuum_ent) }}"
  dev_entities: >-
    {% set all_labels = (labels(vacuum_ent)) | unique %}
    {% set labeled_entities = all_labels | map('label_entities') | sum(start=[]) %}
    {{ (device_entities(dev_id) + labeled_entities) | unique | list }}
  text_helper: "{{ dev_entities | select('match', '^input_text\\..*_rooms_to_clean$') | first | default('none') }}"
  ignored_rooms: !input ignore_rooms
  cleaning_sequence: "{{ state_attr(vacuum_ent, 'cleaning_sequence') | default([], true) | reject('in', ignored_rooms) | list }}"
  summary_filter: !input calendar_summary_match

triggers:
  - event: start
    offset: "0:0:0"
    entity_id: !input calendar_entity
    trigger: calendar

condition:
  # Only continue if the calendar event title contains our search term (case-insensitive)
  - condition: template
    value_template: "{{ (summary_filter | trim | lower) in (trigger.calendar_event.summary | lower) }}"

action:
  # Calls a helper script to check if a specific task exists on the To-Do list
  # The script must return a response_variable (available in HA 2023.7+)
  - action: script.to_do_item_checker
    data:
      search_term: !input todo_search_term
      target_list: !input todo_entity
    response_variable: robot_task_check

  # Execution logic: Only proceed if the maintenance task was NOT found
  - if:
      - condition: template
        value_template: "{{ not robot_task_check.exists }}"
    then:
      # Populate the rooms_to_clean helper with the vacuum's cleaning sequence
      - if:
          - condition: template
            value_template: "{{ text_helper != 'none' and cleaning_sequence is not none }}"
        then:
          - action: input_text.set_value
            target:
              entity_id: "{{ text_helper }}"
            data:
              value: "{{ cleaning_sequence | to_json }}"
      - action: input_select.select_option
        target:
          entity_id: input_select.cleaning_type_selector
          entity_id: !input cleaning_mode_select
        data:
          option: Vacuum and Mop

      # Step 3: Run the user-defined cleaning script
      - action: !input cleaning_script

mode: single
