blueprint:
  name: Dreame Vacuum - Reset and Notify
  domain: automation
  input:
    vacuum_entity:
      name: Vacuum Robot
      selector:
        entity:
          domain: vacuum
          integration: dreame_vacuum
    todo_list:
      name: To-Do List
      selector:
        entity:
          domain: todo
    todo_header_text:
      name: To-Do Header Text
      default: "Robot Cleaning"
      selector:
        text:
    notify_script:
      name: Notification Script
      selector:
        entity:
          domain: script

mode: single

trigger:
  - platform: event
    event_type: dreame_vacuum_task_status
    event_data:
      entity_id: !input vacuum_entity
      completed: true


variables:
  vacuum_ent: !input vacuum_entity
  dev_id: "{{ device_id(vacuum_ent) }}"
  dev_entities: >-
    {% set all_labels = (labels(vacuum_ent)) | unique %}
    {% set labeled_entities = all_labels | map('label_entities') | sum(start=[]) %}
    {{ (device_entities(dev_id) + labeled_entities) | unique | list }}
  text_helper: "{{ dev_entities | select('match', '^input_text\\..*_rooms_to_clean$') | first | default('none') }}"
  currently_cleaned_helper: "{{ dev_entities | select('match', '^input_number\\..*_currently_cleaned$') | first | default('none') }}"

action:
  # Safety check: Only try to clear the queue if the helper was found
  - if:
      - condition: template
        value_template: "{{ text_helper != 'none' }}"
    then:
      - action: input_text.set_value
        target:
          entity_id: "{{ text_helper }}"
        data:
          value: "[]"

  - if:
      - condition: template
        value_template: "{{ currently_cleaned_helper != 'none' }}"
    then:
      - action: input_number.set_value
        target:
          entity_id: "{{ currently_cleaned_helper }}"
        data:
          value: 0

  - action: todo.get_items
    target:
      entity_id: !input todo_list
    data:
      status: needs_action
    response_variable: current_todos

  - action: script.conditional_to_do_creator
    data:
      heading: !input todo_header_text
      body: Replace water and clean the robot

  - action: script.turn_on
    target:
      entity_id: !input notify_script
    data:
      variables:
        message: "The vacuum has finished cleaning and is back at the dock. Please remember to clean the robot and replace the water."

  # Dismiss persistent notifications from the integration
  - action: persistent_notification.dismiss
    data:
      notification_id: "dreame_vacuum_notification"
  - action: persistent_notification.dismiss
    data:
      notification_id: "dreame_vacuum_{{ dev_id }}"
